const ENCHANT_DESCRIPTIONS = {
  resonance: "トークンのレベルに応じてコンボ倍率が増加する（レベル1ごとにコンボ倍率+2）。",
  greed: "現在の所持★数の2倍をコンボ加算値に加える。",
  chain: "コンボ加算値を一律+5する。",
  extra_turn: "目標達成までの手番が +2 される。",
  time_leap: "前のサイクルでスキップしたターン数×3、次のサイクルの全ターンでコンボ加算。",
  combo_fire: "炎の1コンボにつきコンボ+2。",
  combo_water: "雨の1コンボにつきコンボ+2。",
  combo_wood: "風の1コンボにつきコンボ+2。",
  combo_light: "雷の1コンボにつきコンボ+2。",
  combo_dark: "月の1コンボにつきコンボ+2。",
  combo_heart: "ハートの1コンボにつきコンボ+2。",
  enh_drop_fire: "炎ドロップが20%強化で落下。",
  enh_drop_water: "雨ドロップが20%強化で落下。",
  enh_drop_wood: "風ドロップが20%強化で落下。",
  enh_drop_light: "雷ドロップが20%強化で落下。",
  enh_drop_dark: "月ドロップが20%強化で落下。",
  enh_drop_heart: "ハートドロップが20%強化で落下。",
  sf_up_fire: "炎ドロップが少し落ちやすくなる。",
  sf_up_water: "雨ドロップが少し落ちやすくなる。",
  sf_up_wood: "風ドロップが少し落ちやすくなる。",
  sf_up_light: "雷ドロップが少し落ちやすくなる。",
  sf_up_dark: "月ドロップが少し落ちやすくなる。",
  sf_up_heart: "ハートドロップが少し落ちやすくなる。",
  sf_down_fire: "炎ドロップが少し落ちにくくなる。",
  sf_down_water: "雨ドロップが少し落ちにくくなる。",
  sf_down_wood: "風ドロップが少し落ちにくくなる。",
  sf_down_light: "雷ドロップが少し落ちにくくなる。",
  sf_down_dark: "月ドロップが少し落ちにくくなる。",
  sf_down_heart: "ハートドロップが少し落ちにくくなる。",
  opener: "サイクルの1ターン目のみ、コンボ+30。",
  clutch: "サイクルの最終ターンのみ、コンボ倍率にプラス3。",
  rainbow: "4色以上同時消しで、コンボ+7。",
  sniper: "消した色が2色以下の場合、コンボ倍率にプラス2。",
  haste: "操作時間を+4秒延長する。",
  quick_charge: "スキルのチャージ速度が2倍になる。",
  critical: "20%の確率で、この補正倍率が20倍になる。",
  gamble: "ターンごとに -5〜+15 のランダムなコンボ加算。",
  rarity_up: "ショップにレア度の高いトークンが出やすくなる。",
  rarity_down_combo: "ショップにレア度の高いトークンが出にくくなるが、コンボ数+1。",
  shape_match4: "4つ消し1つにつき、コンボ倍率にプラス1。",
  shape_cross: "十字消し1つにつき、コンボ倍率にプラス2。",
  shape_row: "横一列消し1つにつき、コンボ倍率にプラス2。",
  shape_l: "L字消し1つにつき、コンボ倍率にプラス2。",
  shape_square: "正方形消し1つにつき、コンボ倍率にプラス3。",
  efficiency: "このスキルの消費エネルギーを-1する(最小1)。",
  berserk: "操作時間-1秒、コンボ倍率にプラス3。",
  aftershock: "落ちコン発生時、最終コンボ倍率にプラス3。",
  investment: "このトークンの売却価格が購入価格の300%になる。",
  enc_bonus_fire: "炎を消しているとコンボ倍率にプラス2。",
  enc_bonus_water: "雨を消しているとコンボ倍率にプラス2。",
  enc_bonus_wood: "風を消しているとコンボ倍率にプラス2。",
  enc_bonus_light: "雷を消しているとコンボ倍率にプラス2。",
  enc_bonus_dark: "月を消しているとコンボ倍率にプラス2。",
  enc_bonus_heart: "ハートを消しているとコンボ倍率にプラス2。",
  bomb_burst_combo: "ボムドロップが消えた時、追加で5コンボ加算する。",
  accum_technique: "「合計特殊消し回数(4個+1列+L字+十字+四角)」20回につき、コンボ加算+2。",
  magic_resonance: "「スキル使用回数」10回につき、全アクティブスキルの消費エネルギー-2。",
  curse_catalyst: "所持している「呪いトークン」1つにつき、コンボ倍率にプラス1（累積乗算）。",
  magic_echo: "アクティブスキル使用時、50%の確率でチャージを消費しない。",
  compound_interest: "サイクルクリア時、現在の所持スターの10%を追加で獲得する。",
  starfall: "落ちコン（スカイフォール）で降ってくるドロップ of 10% がスタードロップになる。",
  double_edged: "ターン終了時、所持スターを3失うが、そのターンのコンボ倍率にプラス4される。",
  gen_drop_fire: "ターン終了時、炎ドロップを1個生成する。",
  gen_drop_water: "ターン終了時、雨ドロップを1個生成する。",
  gen_drop_wood: "ターン終了時、風ドロップを1個生成する。",
  gen_drop_light: "ターン終了時、雷ドロップを1個生成する。",
  gen_drop_dark: "ターン終了時、月ドロップを1個生成する。",
  gen_drop_heart: "ターン終了時、ハートドロップを1個生成する。",
  gen_drop_repeat: "ターン終了時、リピートドロップを1個生成する。",
  gen_drop_bomb: "ターン終了時、ボムドロップを1個生成する。",
  gen_drop_plus: "ターン終了時、プラスドロップを4個生成する。",
  gen_drop_star: "ターン終了時、スタードロップを4個生成する。",
  gen_drop_move: "ターン終了時、ムーブドロップのカウントを7増やす。",
  convert_to_fire: "ターン終了時、20%の確率でランダムなドロップを炎ドロップに変換する。",
  convert_to_water: "ターン終了時、20%の確率でランダムなドロップを雨ドロップに変換する。",
  convert_to_wood: "ターン終了時、20%の確率でランダムなドロップを風ドロップに変換する。",
  convert_to_light: "ターン終了時、20%の確率でランダムなドロップを雷ドロップに変換する。",
  convert_to_dark: "ターン終了時、20%の確率でランダムなドロップを月ドロップに変換する。",
  convert_to_heart: "ターン終了時、20%の確率でランダムなドロップをハートドロップに変換する。",
  turn_end_refresh: "ターン終了時、20%の確率で盤面をリフレッシュする（次元の再編と同等）。",
  sort_drop_fire: "ターン終了時、70%の確率で炎ドロップを左上から順に整列させる。",
  sort_drop_water: "ターン終了時、70%の確率で雨ドロップを左上から順に整列させる。",
  sort_drop_wood: "ターン終了時、70%の確率で風ドロップを左上から順に整列させる。",
  sort_drop_light: "ターン終了時、70%の確率で雷ドロップを左上から順に整列させる。",
  sort_drop_dark: "ターン終了時、70%の確率で月ドロップを左上から順に整列させる。",
  sort_drop_heart: "ターン終了時、70%の確率でハートドロップを左上から順に整列させる。",
  full_drop_fire: "ターン終了時、10%の確率で盤面を全て炎ドロップにする。",
  full_drop_water: "ターン終了時、10%の確率で盤面を全て雨ドロップにする。",
  full_drop_wood: "ターン終了時、10%の確率で盤面を全て風ドロップにする。",
  full_drop_light: "ターン終了時、10%の確率で盤面を全て雷ドロップにする。",
  full_drop_dark: "ターン終了時、10%の確率で盤面を全て月ドロップにする。",
  full_drop_heart: "ターン終了時、10%の確率で盤面を全てハートドロップにする。",
  double_combo_chance: "10%の確率で基礎コンボ数を2倍にする。"
};


const getEnchantDescription = (id) => ENCHANT_DESCRIPTIONS[id] || "";

const ENCHANTMENTS = [
  {
    id: "resonance",
    name: "レベル共鳴",
    effect: "lvl_mult",
    value: 2,
    rarity: 2, price: 30,
    icon: "layers"
  },
  {
    id: "greed",
    name: "強欲の輝き",
    effect: "star_add",
    value: 2,
    rarity: 3, price: 34,
    icon: "monetization_on"
  },
  {
    id: "chain",
    name: "連鎖の刻印",
    effect: "fixed_add",
    value: 5,
    rarity: 1, price: 22,
    icon: "link"
  },
  {
    id: "extra_turn",
    name: "時の刻印",
    effect: "add_turn",
    value: 2,
    rarity: 2, price: 28,
    icon: "add_alarm"
  },
  {
    id: "time_leap",
    name: "時の跳躍",
    effect: "skip_turn_combo",
    value: 3,
    rarity: 2, price: 28,
    icon: "restore"
  },
  // --- New: Color Combo Bonus Enchantments ---
  { id: "combo_fire", name: "炎の加護", effect: "color_combo", params: { color: "fire" }, value: 2, rarity: 3, price: 24, icon: "whatshot" },
  { id: "combo_water", name: "雨の加護", effect: "color_combo", params: { color: "water" }, value: 2, rarity: 3, price: 24, icon: "water_drop" },
  { id: "combo_wood", name: "森の加護", effect: "color_combo", params: { color: "wood" }, value: 2, rarity: 3, price: 24, icon: "eco" },
  { id: "combo_light", name: "雷の加護", effect: "color_combo", params: { color: "light" }, value: 2, rarity: 3, price: 24, icon: "bolt" },
  { id: "combo_dark", name: "月の加護", effect: "color_combo", params: { color: "dark" }, value: 2, rarity: 3, price: 24, icon: "brightness_2" },
  { id: "combo_heart", name: "癒の加護", effect: "color_combo", params: { color: "heart" }, value: 2, rarity: 3, price: 24, icon: "favorite" },
  // --- Enhanced Drop Enchantments ---
  { id: "enh_drop_fire", name: "炎の強化落下", effect: "enhance_chance_color", params: { color: "fire" }, value: 0.20, rarity: 3, price: 24, icon: "auto_fix_high" },
  { id: "enh_drop_water", name: "雨の強化落下", effect: "enhance_chance_color", params: { color: "water" }, value: 0.20, rarity: 3, price: 24, icon: "auto_fix_high" },
  { id: "enh_drop_wood", name: "風の強化落下", effect: "enhance_chance_color", params: { color: "wood" }, value: 0.20, rarity: 3, price: 24, icon: "auto_fix_high" },
  { id: "enh_drop_light", name: "雷の強化落下", effect: "enhance_chance_color", params: { color: "light" }, value: 0.20, rarity: 3, price: 24, icon: "auto_fix_high" },
  { id: "enh_drop_dark", name: "月の強化落下", effect: "enhance_chance_color", params: { color: "dark" }, value: 0.20, rarity: 3, price: 24, icon: "auto_fix_high" },
  { id: "enh_drop_heart", name: "ハートの強化落下", effect: "enhance_chance_color", params: { color: "heart" }, value: 0.20, rarity: 3, price: 24, icon: "auto_fix_high" },
  // --- Skyfall Boost (Probability Up) ---
  { id: "sf_up_fire", name: "炎の呼び声", effect: "skyfall_boost", params: { color: "fire" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_down" },
  { id: "sf_up_water", name: "雨の呼び声", effect: "skyfall_boost", params: { color: "water" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_down" },
  { id: "sf_up_wood", name: "森の呼び声", effect: "skyfall_boost", params: { color: "wood" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_down" },
  { id: "sf_up_light", name: "雷の呼び声", effect: "skyfall_boost", params: { color: "light" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_down" },
  { id: "sf_up_dark", name: "月の呼び声", effect: "skyfall_boost", params: { color: "dark" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_down" },
  { id: "sf_up_heart", name: "癒の呼び声", effect: "skyfall_boost", params: { color: "heart" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_down" },
  // --- Skyfall Nerf (Probability Down) ---
  { id: "sf_down_fire", name: "炎の静寂", effect: "skyfall_nerf", params: { color: "fire" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_up" },
  { id: "sf_down_water", name: "雨の静寂", effect: "skyfall_nerf", params: { color: "water" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_up" },
  { id: "sf_down_wood", name: "森の静寂", effect: "skyfall_nerf", params: { color: "wood" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_up" },
  { id: "sf_down_light", name: "雷の静寂", effect: "skyfall_nerf", params: { color: "light" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_up" },
  { id: "sf_down_dark", name: "月の静寂", effect: "skyfall_nerf", params: { color: "dark" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_up" },
  { id: "sf_down_heart", name: "癒の静寂", effect: "skyfall_nerf", params: { color: "heart" }, rarity: 3, price: 24, icon: "keyboard_double_arrow_up" },
  { id: "opener", name: "先制の心得", effect: "turn_1_bonus", value: 30, rarity: 3, price: 28, icon: "login" },
  { id: "clutch", name: "土壇場の底力", effect: "last_turn_mult", value: 4.0, rarity: 3, price: 30, icon: "emergency" },
  { id: "rainbow", name: "虹色の加護", effect: "multi_color", value: 7, rarity: 3, price: 30, icon: "palette" },
  { id: "sniper", name: "一点突破", effect: "single_color", value: 3.0, rarity: 3, price: 28, icon: "gps_fixed" },
  { id: "haste", name: "疾風の刻印", effect: "time_ext_enc", value: 4, rarity: 3, price: 28, icon: "speed" },
  { id: "quick_charge", name: "急速チャージ", effect: "charge_boost_passive", rarity: 3, price: 30, icon: "bolt" },
  { id: "critical", name: "会心の一撃", effect: "critical_strike", value: 20, rarity: 3, price: 30, icon: "flash_on" },
  { id: "gamble", name: "運命の悪戯", effect: "random_bonus", rarity: 2, price: 22, icon: "casino" },

  // --- Rarity Modifier Enchantments ---
  { id: "rarity_up", name: "幸運の星", effect: "rarity_up", rarity: 1, price: 28, icon: "stars" },
  { id: "rarity_down_combo", name: "流星の約束", effect: "rarity_down_combo", rarity: 1, price: 28, icon: "brightness_low" },

  // --- 形状別極意エンチャント (Geometry Split) ---
  { id: "shape_match4", name: "四連の極意", effect: "shape_match4", value: 2.0, rarity: 3, price: 24, icon: "category" },
  { id: "shape_cross", name: "十字の極意", effect: "shape_cross", value: 3.0, rarity: 3, price: 24, icon: "category" },
  { id: "shape_row", name: "一列の極意", effect: "shape_row", value: 3.0, rarity: 3, price: 24, icon: "category" },
  { id: "shape_l", name: "L字の極意", effect: "shape_l", value: 3.0, rarity: 3, price: 24, icon: "category" },
  { id: "shape_square", name: "正方形の極意", effect: "shape_square", value: 4.0, rarity: 3, price: 24, icon: "category" },

  { id: "efficiency", name: "魔力節約", effect: "cost_down", rarity: 3, price: 30, icon: "savings" },
  { id: "berserk", name: "狂戦士の刻印", effect: "berserk_mode", value: 4.0, rarity: 3, price: 30, icon: "dangerous" },
  { id: "aftershock", name: "追撃の心得", effect: "skyfall_mult", value: 4.0, rarity: 3, price: 28, icon: "waves" },
  { id: "investment", name: "資産価値", effect: "high_sell", rarity: 2, price: 18, icon: "account_balance_wallet" },
  // --- 色別連舞エンチャント (1.2倍) ---
  { id: "enc_bonus_fire", name: "炎の連舞", effect: "color_multiplier_enc", params: { color: "fire" }, value: 3.0, rarity: 3, price: 24, icon: "animation" },
  { id: "enc_bonus_water", name: "雨の連舞", effect: "color_multiplier_enc", params: { color: "water" }, value: 3.0, rarity: 3, price: 24, icon: "animation" },
  { id: "enc_bonus_wood", name: "風の連舞", effect: "color_multiplier_enc", params: { color: "wood" }, value: 3.0, rarity: 3, price: 24, icon: "animation" },
  { id: "enc_bonus_light", name: "雷の連舞", effect: "color_multiplier_enc", params: { color: "light" }, value: 3.0, rarity: 3, price: 24, icon: "animation" },
  { id: "enc_bonus_dark", name: "月の連舞", effect: "color_multiplier_enc", params: { color: "dark" }, value: 3.0, rarity: 3, price: 24, icon: "animation" },
  { id: "enc_bonus_heart", name: "癒の連舞", effect: "color_multiplier_enc", params: { color: "heart" }, value: 3.0, rarity: 3, price: 24, icon: "animation" },

  // --- New Stat-Based Enchantments ---
  { id: "magic_echo", name: "魔力反響", effect: "magic_echo", value: 0.50, rarity: 3, price: 36, icon: "repeat" },
  { id: "compound_interest", name: "複利の導き", effect: "compound_interest", value: 0.10, rarity: 3, price: 30, icon: "trending_up" },
  { id: "curse_catalyst", name: "呪力変換", effect: "curse_catalyst", value: 2.0, rarity: 3, price: 36, icon: "auto_awesome_motion" },
  { id: "bomb_burst_combo", name: "誘爆の雷管", effect: "bomb_burst_combo", value: 5, rarity: 3, price: 28, icon: "explosive" },
  { id: "accum_technique", name: "技巧の蓄積", effect: "stat_shape_all", value: 2, rarity: 3, price: 28, icon: "history_edu" },
  { id: "magic_resonance", name: "魔力共鳴", effect: "stat_skill_use", value: 2, rarity: 3, price: 30, icon: "record_voice_over" },
  { id: "starfall", name: "星呼びの刻印", effect: "starfall", value: 0.10, rarity: 3, price: 30, icon: "star" },
  { id: "double_edged", name: "諸刃の刻印", effect: "double_edged", value: 4, rarity: 3, price: 28, icon: "exposure" },
  { id: "gen_drop_fire", name: "炎生成の刻印", effect: "gen_drop_color", params: { color: "fire" }, rarity: 2, price: 20, icon: "whatshot" },
  { id: "gen_drop_water", name: "雨生成の刻印", effect: "gen_drop_color", params: { color: "water" }, rarity: 2, price: 20, icon: "water_drop" },
  { id: "gen_drop_wood", name: "風生成の刻印", effect: "gen_drop_color", params: { color: "wood" }, rarity: 2, price: 20, icon: "air" },
  { id: "gen_drop_light", name: "雷生成 of 刻印", effect: "gen_drop_color", params: { color: "light" }, rarity: 2, price: 20, icon: "bolt" },
  { id: "gen_drop_dark", name: "月生成の刻印", effect: "gen_drop_color", params: { color: "dark" }, rarity: 2, price: 20, icon: "nightlight_round" },
  { id: "gen_drop_heart", name: "癒生成の刻印", effect: "gen_drop_color", params: { color: "heart" }, rarity: 2, price: 20, icon: "favorite" },
  { id: "gen_drop_repeat", name: "反響生成の刻印", effect: "gen_drop_repeat", rarity: 3, price: 24, icon: "repeat" },
  { id: "gen_drop_bomb", name: "爆発生成の刻印", effect: "gen_drop_bomb", rarity: 3, price: 24, icon: "explosive" },
  { id: "gen_drop_plus", name: "強化生成の刻印", effect: "gen_drop_plus", rarity: 2, price: 22, icon: "add_circle" },
  { id: "gen_drop_star", name: "星屑生成の刻印", effect: "gen_drop_star", rarity: 3, price: 26, icon: "star_rate" },
  { id: "gen_drop_move", name: "加刻の刻印", effect: "gen_drop_move", rarity: 3, price: 28, icon: "more_time" },
  { id: "convert_to_fire", name: "炎化の刻印", effect: "convert_to_color", params: { color: "fire" }, rarity: 2, price: 18, icon: "whatshot" },
  { id: "convert_to_water", name: "雨化の刻印", effect: "convert_to_color", params: { color: "water" }, rarity: 2, price: 18, icon: "water_drop" },
  { id: "convert_to_wood", name: "風化の刻印", effect: "convert_to_color", params: { color: "wood" }, rarity: 2, price: 18, icon: "air" },
  { id: "convert_to_light", name: "雷化の刻印", effect: "convert_to_color", params: { color: "light" }, rarity: 2, price: 18, icon: "bolt" },
  { id: "convert_to_dark", name: "月化の刻印", effect: "convert_to_color", params: { color: "dark" }, rarity: 2, price: 18, icon: "nightlight_round" },
  { id: "convert_to_heart", name: "癒化の刻印", effect: "convert_to_color", params: { color: "heart" }, rarity: 2, price: 18, icon: "favorite" },
  { id: "turn_end_refresh", name: "再編の刻印", effect: "turn_end_refresh", rarity: 3, price: 30, icon: "refresh" },
  { id: "sort_drop_fire", name: "炎整の刻印", effect: "sort_drop_color", params: { color: "fire" }, rarity: 2, price: 22, icon: "sort" },
  { id: "sort_drop_water", name: "雨整の刻印", effect: "sort_drop_color", params: { color: "water" }, rarity: 2, price: 22, icon: "sort" },
  { id: "sort_drop_wood", name: "風整の刻印", effect: "sort_drop_color", params: { color: "wood" }, rarity: 2, price: 22, icon: "sort" },
  { id: "sort_drop_light", name: "雷整の刻印", effect: "sort_drop_color", params: { color: "light" }, rarity: 2, price: 22, icon: "sort" },
  { id: "sort_drop_dark", name: "月整の刻印", effect: "sort_drop_color", params: { color: "dark" }, rarity: 2, price: 22, icon: "sort" },
  { id: "sort_drop_heart", name: "癒整の刻印", effect: "sort_drop_color", params: { color: "heart" }, rarity: 2, price: 22, icon: "sort" },
  { id: "full_drop_fire", name: "炎天の刻印", effect: "full_drop_color", params: { color: "fire" }, rarity: 3, price: 36, icon: "brightness_high" },
  { id: "full_drop_water", name: "雨天の刻印", effect: "full_drop_color", params: { color: "water" }, rarity: 3, price: 36, icon: "cloudy_snowing" },
  { id: "full_drop_wood", name: "嵐天の刻印", effect: "full_drop_color", params: { color: "wood" }, rarity: 3, price: 36, icon: "cyclone" },
  { id: "full_drop_light", name: "震天の刻印", effect: "full_drop_color", params: { color: "light" }, rarity: 3, price: 36, icon: "thunderstorm" },
  { id: "full_drop_dark", name: "夜天の刻印", effect: "full_drop_color", params: { color: "dark" }, rarity: 3, price: 36, icon: "dark_mode" },
  { id: "full_drop_heart", name: "慈天の刻印", effect: "full_drop_color", params: { color: "heart" }, rarity: 3, price: 36, icon: "favorite" },
  { id: "double_combo_chance", name: "強撃の刻印", effect: "double_combo_chance", rarity: 3, price: 30, icon: "double_arrow" }
];

export { ENCHANT_DESCRIPTIONS, getEnchantDescription, ENCHANTMENTS };
